### ISSUE TITLE
Learning to do refactoring in my project (opinions, tips, suggestions and discussion are welcomed)

### ISSUE THREAD

**Issue by ysinotelodigo** [goldbergyoni/nodebestpractices#1076]
Dear node-best-practices community,

First of all, I would like to say that this repository is really useful and a great idea. I have started to read it and I am putting the best practices in practice for a project. (The project size is not totally important because the most important idea is to learn). In a near future, I would like to create a blog/repository with simple shared projects to show the good practices and bad practices (using code and funtional projects). The idea will go beyond to the node.js low-level code. I know that this blog/repository would be less neutral but it could be useful to people to want to get best practices step by step. Thus, your opinion and tips are so import to me.

I started to change the structure of my project from role folders to components self-contained folder. (To reach the '1.1 Structure your solution by components')
Before:
![imagen](https://user-images.githubusercontent.com/3694734/133574468-620d4871-ec6d-4bf2-b858-06aa1ab589f4.png)
Now:
![imagen](https://user-images.githubusercontent.com/3694734/133574657-c31af812-bce6-48e3-920f-2b9a5860d2e9.png)

The second guide ('1.2 Layer your components, keep the web layer within its boundaries') of the best practices already fulfilled it.
The fourth guide ('1.4 Separate Express 'app' and 'server''), I have carried it out too.

Questions:

1. Do you think that the self-contained components should have its own router? In this case, Should I have to have a global router too or reference the modules in 'app.js' file?
2. The fifth guide (1.5 Use environment aware, secure and hierarchical config) recomends some 3rd libraries (rc, nconf, config, and convict). I undesrtand that dotenv is not totally good because it does not control several differents environments (development, production, testing...), is it?
3. I have a config.js to provide the mongodb client connection. It is shared by all components... because they connect to the database. Should I put this file to each components or integrate its code lines to xxxx.db.js?

![imagen](https://user-images.githubusercontent.com/3694734/133577751-13fcf92c-9f11-4432-a82e-5afedcebf985.png)

If you want to reply only one question, your replying is welcomed =) 
If you see a wrong structure, idea and implementing, do not hesistate to tell me.

**Comment by goldbergyoni** [comment]
@ysinotelodigo Welcome aboard. Sorry for the late reply, I was in a long vacation.

See my thoughts below.

Your Questions:

1. Do you think that the self-contained components should have its own router? In this case, Should I have to have a global router too or reference the modules in 'app.js' file?

Each component should hold everything independently. One exception: Do you deploy a single process, component=process (e.g. via docker) or all-components=1-process. If the first option, then nothing can be at the root since only the component folder will get deployed. If the 2nd option, you need to define the global router and pass to the children

2. The fifth guide (1.5 Use environment aware, secure and hierarchical config) recomends some 3rd libraries (rc, nconf, config, and convict). I undesrtand that dotenv is not totally good because it does not control several differents environments (development, production, testing...), is it?

dotend is not recommended by us because it does not fail fast (schema), has no hierarchical config and encourages creating config per environment which is tedious


3. I have a config.js to provide the mongodb client connection. It is shared by all components... because they connect to the database. Should I put this file to each components or integrate its code lines to xxxx.db.js?

Since it's just 2 lines, I would repeat myself

p.s. If you need to share things among components, use a library
