### ISSUE TITLE
French translation

### ISSUE THREAD

**Issue by gaspaonrocks** [goldbergyoni/nodebestpractices#129]
If you want i can help with french translation...

**Comment by i0natan** [comment]
@gaspaonrocks sounds amazing, would you like to lead this work and find together others that will help you?

p.s. your name will be added to the core contributors + will be on top of the French page

**Comment by gaspaonrocks** [comment]
@i0natan I'll start a readme.french.md then and wait for your instruction for the pull request.

**Comment by i0natan** [comment]
@gaspaonrocks  - French translation can be officially kicked-off. You're the lead! I'll be at your disposal should you need anything. Please create a branch for this work and PR to master once it's 100% done.

I would ask/recommend only 2 important guidelines:

Keep the same content & formatting - the focus is on translation, should anyone want to modify the content or the graphics - let's PR first in English and them translate to French
Duplicate pages - the content should be translated over a page duplication. Readme.MD became Readme.french.MD, all other files should be duplicated similarly. So the number of English & French pages should be the same. Will create a bold link from the English home page to the French home page (with bold credit of course...).

**Comment by adaube** [comment]
I would love to be able to help on this PR. I see that @gaspaonrocks has the lead.

How can I help?

**Comment by gaspaonrocks** [comment]
@adaube If you want we can split the work. Each of us having his pages to translate. 

I started with the main page but I didn't realise it was massive. Maybe start with the smaller sections ?

**Comment by adaube** [comment]
@gaspaonrocks that sounds great. Your approach of breaking the work down into smaller chunks is exactly how I like to roll! I'll fork and dive deeper this weekend, or sooner if I can carve out time.

**Comment by i0natan** [comment]
sounds great. You may share in some French groups (FB, etc) to see whether other would like to join

**Comment by Annouar** [comment]
Hey !
If you guys need some help with French translation, let me know

**Comment by gaspaonrocks** [comment]
@Annouar 
Hey ! Sure, you can translate any parts. Any help is appreciated.

I have almost done the `/sections/projectstructure` folder, but i see that thincomponents.md and breakintocomponents.md is the exact same file. Any idea why @i0natan ?

I fixed some minor typos in the english files as well.

I'll PR once I'm done with this folder.

**Comment by i0natan** [comment]
@gaspaonrocks @adaube @Annouar sounds great, really anxious to see it live

**Comment by Yaty** [comment]
Hey ! I'll be happy to contribute for the french translation :) What is not currently being translated ?

**Comment by NTurchi** [comment]
Hi! I have seen that the French translation isn't done yet. I could work on it if you need someone.

**Comment by i0natan** [comment]
@NTurchi Bienvenue! 👍 

@gaspaonrocks @adaube @Annouar I'd be glad to hear your thoughts (see @NTurchi message) and progress so far?

**Comment by gaspaonrocks** [comment]
Hello everyone, 

Sorry for the lack of news about the french translation, but I have been swamped with work, which is a good thing. For everyone working on the French translation, you can do small files, and submit a PR for a review. 

You announce what files you are working on before submitting the PR, that way duplicate work will be avoided.

I'll try and be more available.

Again, sorry and thanks to everyone involved.

**Comment by NTurchi** [comment]
@gaspaonrocks If nobody work on it, I can translate "**2.1 Use Async-Await or promises for async error handling**" and also the attached article below **"Read More: avoiding callbacks"**

**Comment by gaspaonrocks** [comment]
Yes !  I'll try and come up with a table with pages, the translator, and the status.

**Comment by pascaloliv** [comment]
I can give my help to review or contribute. 👍

**Comment by Berkmann18** [comment]
@gaspaonrocks Any progress on that?

**Comment by joaquinox** [comment]
I'd be happy to contribute if this issue is still open! 🇫🇷

**Comment by i0natan** [comment]
@joaquinox Welcome aboard!

It's super relevant. Maybe @gaspaonrocks @NTurchi can share their progress so you join or at least not start from a clean slate?

**Comment by joaquinox** [comment]
Thanks @i0natan! I'll wait for instructions from @gaspaonrocks or @NTurchi before moving forward then 👍

**Comment by i0natan** [comment]
@gaspaonrocks or @NTurchi Maybe can you kindly just share with @joaquinox the current status so he can progress your great work from the right point?

**Comment by goldbergyoni** [comment]
@gaspaonrocks @NTurchi One more try, maybe you can just share a status update? 🙏

**Comment by NTurchi** [comment]
@goldbergyoni  Sorry for this late reply. A PR has been on the [French repo version] at the beginning of this year (https://github.com/gaspaonrocks/nodebestpractices/pull/1) but I didn't get any follow-up. Thus, I have not started to go deeper into the translation. @gaspaonrocks Any update?

**Comment by goldbergyoni** [comment]
Thank you @NTurchi :)

@joaquinox, In that case, I suggest you just fork the French repo of @gaspaonrocks?

**Comment by joaquinox** [comment]
Thanks for the green light @goldbergyoni, I'll get to work this weekend 👍

**Comment by goldbergyoni** [comment]
> Thanks for the green light @goldbergyoni, I'll get to work this weekend 👍

🎈 🎉 

Let me whether I can help in any form

**Comment by l-portet** [comment]
Hey, if you need help I'd be happy to contribute! 😊

**Comment by forresst** [comment]
@goldbergyoni Despite several attempts, the translation is no longer progressing.

So I started translating into French (taking up and adapting what had already been done). For this, I made a fork of the repository[`goldbergyoni/nodebestpractices`](https://github.com/forresst/nodebestpractices/) and I created a branch[`french-translation`](https://github.com/forresst/nodebestpractices/tree/french-translation).

My [first commit](https://github.com/forresst/nodebestpractices/commit/93bdceaa9c637d97e6b1816125e81c84127ed70e) just copied all the markdown files from the original text to copy them into `xxxx.french.md` files.

The following commits are the first translations. 

I made one commit per file. For example, one for the file `writing-guidelines.md`.  Thanks to my first commit explained above, you can see both the original version and the replacements made by the French translation. Here is the [commit](https://github.com/forresst/nodebestpractices/commit/da04e0a9adb61989045c79cc22650b5eed09c5bc) of the `writing-guidelines.md` file.

My goal is to finish on 31 January 2020.

Of course all help is welcome: translations, proofreading, discussion

I have created an [issue](https://github.com/forresst/nodebestpractices/issues/1) to track the progress of translations.
As I write his lines, 15% of the translation is done.

If people volunteer to translate into French, leave me a comment in this [issue](https://github.com/forresst/nodebestpractices/issues/1) so that I can assign you the translation of a file. This prevents several people from working on the same file.

**Comment by joaquinox** [comment]
@forresst Thanks for keeping this going. Apologies for not getting more involved in this yet, I have recently started a new role and have a little daughter that keeps me busy 🤦‍♂ 

I hope to get started asap!

**Comment by corentindesfarges** [comment]
Hi
I'd be happy to contribute :-) Just tell me how I can help 👷

**Comment by forresst** [comment]
> Hi
> I'd be happy to contribute :-) Just tell me how I can help 👷

@corentindesfarges First of all, thank you for your help. The simplest: 
1. Choose the file you want to translate from those that are not assigned in thise [issue](https://github.com/forresst/nodebestpractices/issues/1) and leave me a comment in this [issue](https://github.com/forresst/nodebestpractices/issues/1) so that I can assign you the translation of a file. 
2. Then fork my own [fork](https://github.com/forresst/nodebestpractices/) and work on the [`french-translation`](https://github.com/forresst/nodebestpractices/tree/french-translation) branch
3. When the work is done, propose a PR on **my fork**
4. I will review your work

If you only want to review my work, you can post comments directly on my commits in Github

**Comment by goldbergyoni** [comment]
> have a little daughter that keeps me busy 🤦‍♂

❤️

**Comment by forresst** [comment]
This subject is still in progress, I'm behind schedule but the translation is progressing well. Moreover I received help for translation and proofreading. And that's great.

**Comment by goldbergyoni** [comment]
Hey @tkhadir ! Welcome 🎊, Thanks for approaching in #831 !

Let's continue the discussion here.

Dear @gaspaonrocks @samueldjones24 @corentindesfarges @forresst, Would you kindly help @tkhadir get on board and understand how to continue your wonderful work? Maybe can share with him some high-level status?

**Comment by tkhadir** [comment]
hello @goldbergyoni thanks for all :)

**Comment by forresst** [comment]
Sorry I've been away for more than 9 months, but I'm back to move on. I advise to follow the instructions of [this comment](https://github.com/goldbergyoni/nodebestpractices/issues/129#issuecomment-565445523)

**Comment by forresst** [comment]
Just to give you an update, 41 out of 87 files are translated and reviewed. Currently 10 are in progress or awaiting review.

I regularly update the translation according to the modifications applied to the original English version.

Anyone interested in translation and/or review is welcome.

**Comment by goldbergyoni** [comment]
@forresst Awesome progress. Is the homepage translated? If yes, shall we publish this already and then wait for the internal files?

cc @kevynb

**Comment by forresst** [comment]
@goldbergyoni @kevynb 

The main page (README) is translated progressively. Currently, for the main page, parts 1, 2, 3 and 4 are translated and reviewed, part 5 is awaiting proofreading (Going To Production Practices). Part 6 is being translated (Security).

We have a main branch ([french-translation](https://github.com/forresst/nodebestpractices/tree/french-translation)) of all translations done and reviewed. An [issue](https://github.com/forresst/nodebestpractices/issues) to follow the progress of the translations.

Two possibilities:
- I can do a PR for the french-translation branch, this allows to have 47 out of 87 translated files and parts 1,2, 3 and 4 of the README.
- I can focus on the translation of the main page, and provide the complete main page translation with all the other files already translated and reviewed.


What's your opinion?

**Comment by goldbergyoni** [comment]
Thank you @forresst 

I like the 2nd option, focusing on the home page only for now. Let French readers read the main part at least, then gradually later process individual files. Maybe also @tkhadir and @corentindesfarges wish to be part of the home page writing.

**Comment by tkhadir** [comment]
Hello @forresst , @goldbergyoni 

I will read this with pleasure this night :),

**Comment by forresst** [comment]
@goldbergyoni Ok, I focus on the translation of the main page

@tkhadir You can already review [part 5](https://github.com/forresst/nodebestpractices/pull/15) in priority

**Comment by goldbergyoni** [comment]
@forresst  @tkhadir Awesome. Let me know how I can help.
