### ISSUE TITLE
Revert line-length markdownlint setting

### ISSUE THREAD

**Issue by js-kyle** [goldbergyoni/nodebestpractices#552]
https://github.com/goldbergyoni/nodebestpractices/pull/551

The suggestion is to disable ignore the rule `MD013` in `.operations/.markdownlint.json`

**Comment by oshliaer** [comment]
Thanks for start the discussion!

I thinks a linting of md is a big step to forward.

OK. I have a problem with `MD013.lineLength`.

To translate, I need to go to a specific line so that the number of lines matches at the end. Thus, I verify that my translation is up to date. This is one of the important milestones in the quality of the product.

Our languages are so different that we cannot guarantee the same number of lines. So, we will lose one of the quality parameters. It looks like a high price.

If you are interested, I can give a description of the translation process, which requires a minimum of effort and returns high quality.

**Comment by js-kyle** [comment]
@oshliaer thanks for bringing this to light - it was something I really didn't anticipate! It is important if it impacts quality - as this was aiming to improve quality 😄

Do you see any other issues or was it mainly the change related to `MD013`?

**Comment by oshliaer** [comment]
- [x] - "default" - I am sure that for all left-handed languages this will most likely be correct
- [x] - "MD033" - Inline HTML
- [x] - "MD001" - Header levels should only increment by one level at a time
- [ ] - "MD013"  - Line length. We may have problems for different languages
- [x] - "MD039"  - Spaces inside link text

I checked this for the Russian file. This is basically `MD013`. To fix this, it will take me several hours and I can not guarantee the set numbers of lines.

![Untitled](https://user-images.githubusercontent.com/5027939/63645969-5c192000-c712-11e9-8504-ac8574c85a59.png)

**Comment by js-kyle** [comment]
OK cool. In the next day or so, I will create a PR to revert the line changes to README.md, but retain the other changes

**Comment by oshliaer** [comment]
I really hope that I did not cause you any inconvenience or concern.

**Comment by js-kyle** [comment]
No, thank you! Good to raise it as an issue early so we can catch the issue

**Comment by js-kyle** [comment]
@oshliaer I have created https://github.com/goldbergyoni/nodebestpractices/pull/559 to revert these problematic changes

**Comment by oshliaer** [comment]
Thanks for this!

I updated the translation. Now he's on the crest of a wave! :surfing_man:

**Comment by js-kyle** [comment]
Perfect, thanks for that!
