### ISSUE TITLE
Recommend asserting the presence of env variables required for running the app

### ISSUE THREAD

**Issue by halfzebra** [goldbergyoni/nodebestpractices#561]
Sometimes environment variables are used by the code, which is not exercised at startup, e.g. one of the routes of the server.
If the variable is not set, the application will fail at run-time, potentially in production, affecting the end-users.

The guide already recommends minimizing the number of env vars, so I feel like the next step would be recommending on asserting the presence of all required env vars at start-up.

```js
const assert = require('assert')

assert(
  ['dev','prod'].includes(proccess.env.NODE_ENV),
  'NODE_ENV env variable is required for application to run'
)
```

This way we can make sure the app will fail asap if required env vars are not present.

What do you think?

**Comment by goldbergyoni** [comment]
That's a very good point IMO, shall we maybe include it within '2.11 Fail fast, validate arguments using a dedicated library'?

p.s. Where is it recommended to minimize env vars?

**Comment by halfzebra** [comment]
Thanks for the feedback!

Yes, this is definitely about failing fast :+1:

I completely agree with recommendation about [Joi](https://github.com/goldbergyoni/nodebestpractices/blob/master/sections/errorhandling/failfast.md#code-example-validating-complex-json-input-using-joi) for the input, but [assert](https://nodejs.org/api/assert.html) feels like a better option, since it is already in the Node distribution. I'd say the easiest place to describe env var validation would be adding a code example similar to proposed in the issue to [this file](https://github.com/goldbergyoni/nodebestpractices/blob/master/sections/projectstructre/configguide.md#code-example--hierarchical-config-helps-to-find-entries-and-maintain-huge-config-files).

> p.s. Where is it recommended to minimize env vars?

It's my understanding of the following point:

> setting all the keys using process environment variables becomes very tedious when in need to inject 100 keys (instead of just committing those in a config file)
> https://github.com/goldbergyoni/nodebestpractices/blob/master/sections/projectstructre/configguide.md

What do you think?

**Comment by goldbergyoni** [comment]
Apologies, for the late response, I somehow missed your reply.

> I completely agree with recommendation about [Joi](https://github.com/goldbergyoni/nodebestpractices/blob/master/sections/errorhandling/failfast.md#code-example-validating-complex-json-input-using-joi) for the input, but [assert](https://nodejs.org/api/assert.html) feels like a better option

I'm not sure whether assert is the right tool for the mission because config validation has a long list of requirements that some libs address them all (see how elegant npm/convict is) while assert addresses only one. As a developer, I prefer not to iterate over 30 env vars and assert rather declare once my config schema and get all the features at once: validation, extraction, default value, etc. In addition, assert exceptions don't include the failure reason which is necessary for the web layer to map into a meaningful error (e.g. return to the user a description of http 400 error was returned). Does this make sense?



> I'd say the easiest place to describe env var validation would be adding a code example similar to proposed in the issue to [this file](https://github.com/goldbergyoni/nodebestpractices/blob/master/sections/projectstructre/configguide.md#code-example--hierarchical-config-helps-to-find-entries-and-maintain-huge-config-files).

Good idea, maybe also add convict examples which also validate the input?



> It's my understanding of the following point:

Yes, just to be more specific: I would recommend not to use env var when you just don't need to expose this config key. If you do need to allow the ops team to adjust 100 keys - env vars are fine.

**Comment by halfzebra** [comment]
No worries and thanks for your reply!

I usually use assert and build a small helper that iterates over a schema over the env vars(if there are more than 3-5 of them), just to run a dependency-free life. I like how [convict](https://www.npmjs.com/package/convict) does it and I think this approach(or similar) should be the industry standard 🙂

I'm up for adding the example of using convict 👍

**Comment by goldbergyoni** [comment]
> I'm up for adding the example of using convict 👍

Yes! let's do it and emphasize the convict approach in bullet 1.5?
