### ISSUE TITLE
Thai translation

### ISSUE THREAD

**Issue by heyfirst** [goldbergyoni/nodebestpractices#670]
Hello folks,

I would like to ask you, contributors. Could I help to translate in Thai? 

because NodeJS is quite popular in Thailand, especially, in beginner because it's javascript(easy to learn) and advanced users as well.

by the way, I can find my 2-3 friends to help me translate together.

**Comment by tulathorn** [comment]
Hey friends @heyfirst 

I have found your issue accidentally. By the way, I just want to drop the message that if it happen, I'm in.

I think to translate this repo to Thai will create huge benefit to the tech industry. Now, NodeJS is one of the most popular programming in Thailand, from newbies to professional. In addition, some of people in Thailand have a very big misunderstanding in NodeJS development which can see clearly see in several facebook groups. This translate might help us understand the NodeJS more.

Another issue it Thailand is the language barrier, not all of developer understand english clearly. I found that some of student want to learn programming but they cannot because of english.

Since now, most of my daily activities need to done remotely. I think I can allocate some time-sloth to contribute and I would love to do it!

**Comment by kevynb** [comment]
Hello @heyfirst @tulathorn , that seems like a wonderful idea! Thanks for taking the time to submit it.
You are more than welcome if you want to translate nodebestpractices in thai! Just create a fork and start your translation on it.
You will be able to manage multiple contributors directly on your fork.

For every file that you translate, copy it and add `.thai` before the `.md` extension (like for the other languages).

You can create a PR adding the link to your fork while the translation is incomplete/pending in the `Translations in progress` section.

Do not hesitate to ask questions if you need :)

**Comment by goldbergyoni** [comment]
@heyfirst @tulathorn Welcome aboard! Great to have you here with us

@kevynb Are you willing to accompany the Thai translation (Search Thai)?
https://github.com/goldbergyoni/nodebestpractices/blob/master/.operations/operations-manual.md

p.s. If you need further instructions template, visit here:
https://github.com/goldbergyoni/nodebestpractices/blob/master/.operations/.common-answers.md

**Comment by heyfirst** [comment]
@goldbergyoni Thanks!

**Comment by kevynb** [comment]
Yes, so let's do it following the operations manual 😉 

It seems that I missed some points, so here are some more guidelines:
   * Focus on translation, not content editing - the focus is on translation, should anyone want to modify the content or the graphics - let's PR first in English and then translate to other languages. Also the format of the text should remain intact (same design)
    
* Collaborate - once you do the basic setup (branch, duplicate pages), we can announce the work on a new language and get others involved and help you in translation (if you wish)
    
We're here to help - let us know whether we can do anything to support you. We can Tweet about this work, put homepage banner or anything else
