### ISSUE TITLE
Feedback before writing: Prefer smaller Docker base images 

### ISSUE THREAD

**Issue by BrunoScheufler** [goldbergyoni/nodebestpractices#713]
Context: This is used to share my initial draft of a new best practice to get feedback before writing it down.

Title: Prefer smaller Docker base images

TL&DR:

- Large images lead to higher exposure to vulnerabilities
- Often, you don't need certain packages installed at runtime that are needed for building
- The larger the base system, the higher the resource consumption
- Pulling and storing larger images gets more expensive at scale
- Images can be shrunk by utilizing multi-stage builds #711 
- Size comparison: Node.js v14.4.0 image is ~345MB in size versus ~39MB for the Alpine version
- Minimal images might lack common libraries needed for building native modules (gcc on regular images vs musl on Alpine), or packages useful for debugging (e.g. curl that's not pre-installed on Alpine base images)

**Comment by goldbergyoni** [comment]
Great start.

Couple of thoughts:
1. Maybe the title should be 'Prefer smaller *base* images' because few other bullets deal with size: multi-stage, npm i --production, etc
2. Some numbers can make this more tangible, e.g. "The default base image size is 700MB while the Slim and Alpine versions are xMB & yMB respectively"
3. The reader is probably curious to read what is the price of shaving the size of the image: what for example was trimmed from the image?

**Comment by BrunoScheufler** [comment]
Fully agree, especially for the metrics, added an example for the Node.js image (fittingly).

**Comment by BrunoScheufler** [comment]
This is now added in #732

**Comment by kevynb** [comment]
#732 is merged, closing for housekeeping 😄
