### ISSUE TITLE
Question about: 2.6 Exit the process gracefully when a stranger comes to town

### ISSUE THREAD

**Issue by WillXing** [goldbergyoni/nodebestpractices#763]
When a web service process is running, sometimes it can have many traffics on the process.
If 1 traffic somehow throw an uncaught exception and entire process shut down, won't that cause all traffic on the process fail? 
Is it too aggressive approach?

**Comment by goldbergyoni** [comment]
Yes, you're right. This is why bullet 2.3 exists: "2.3 Distinguish operational vs programmer errors"

Does this make sense?

**Comment by WillXing** [comment]
Hi @goldbergyoni , I am still not fully understand yet, let's say when to have user A and B's traffic on the process:
 - user B somehow throw an uncaught error because of his specific operation/data.
 - user A are all good, waiting for the response from server

If I understand correctly, the process got exit as a whole then user A will also lose its health connection.
Shouldn't this case just gracefully end the connection for user C better?

**Comment by goldbergyoni** [comment]
> If I understand correctly, the process got exit as a whole then user A will also lose its health connection.
Shouldn't this case just gracefully end the connection for user C better?

You understand correctly. But, going with bullet 2.3, the process will exit only when a catastrophic thing happens, something that is even worse than letting A & C down. Example: should the connection to the DB is lost and not recoverable, there almost no point in keep serving requests, sometimes severe internal error might also lead to incorrect behaviour. Only in these cases, we prefer to notify the monitoring and restart the process otherwise we have a zombie process. Good testing and practices will make this situation rare.
