### ISSUE TITLE
Section 8 but for people who can't run on the node docker image?

### ISSUE THREAD

**Issue by JaredCE** [goldbergyoni/nodebestpractices#800]
For whatever reason, we want to run node on Ubuntu Docker images... Now you might go "well that's crazy" but that's how it is.

Is it worth doing section 8 for teams/people in similar positions where they can't use one of the node docker images and have to use something else?

I've been looking for similar best practice guides, as i doubt my docker setup for running on Ubuntu, is best practice.

**Comment by kevynb** [comment]
Hello @JaredCE,

To my mind, most of the bullet points of section 8 can be applied to an ubuntu docker image except maybe the 8.10.
If you absolutely need to use an ubuntu image, use an ubuntu image 😄  

You can still use a multi-stage dockerfile, a `.dockerignore`, avoid using `npm start` and all the other recommendations even without using the node docker image.

Can you tell me which bullet-point you think do not work for your use case? We may try to adapt them if needed 🙂

**Comment by goldbergyoni** [comment]
I (usually, if not always) second @kevynb thoughts 😉

**Comment by JaredCE** [comment]
@kevynb You're right...

With https://github.com/goldbergyoni/nodebestpractices/blob/master/sections/docker/graceful-shutdown.md... if you're using docker-compose, I think you can use the init command/argument rather than using Tini?  my docker-foo is not very good and this might be a case of because i'm using ubuntu rather than a node image.  I'd defer to anyone with superior knowledge.

**Comment by kevynb** [comment]
Using the `--init` argument might do it indeed. It works not only with docker-compose but also if you're starting your containers manually. 

However I think that if you start your node process in the Docker container with `CMD ['node', 'myfile.js']` the node process will be assigned PID 1 and will receive all the signals sent to the container, even if you're based on an ubuntu image.

**It's important to use an array** instead of a string to run the command. [It's all explained here](https://github.com/goldbergyoni/nodebestpractices/blob/master/sections/docker/bootstrap-using-node.md).
