### ISSUE TITLE
New Security BP Idea: If possible, avoid using password as authentication. Instead, rely on 3rd party services.

### ISSUE THREAD

**Issue by SuspiciousLookingOwl** [goldbergyoni/nodebestpractices#929]
This is not only applicable to Node, but I think it's still a good idea to add this to the best practice.

Instead of implementing your own authentication using email / username and password, rely on 3rd party services (if possible), like Facebook / Google / Github OAuth, which in most cases will have better security than our application.

This avoids storing hashed password (which is still possible to crack) in our database. So in worst case scenario if your database get attacked and leaked, no user password can be found.

**Comment by josh-hemphill** [comment]
I'm not sure it's necessarily a "best practice", I think it might make sense to say that's best practice if you don't want or can't commit to taking login security very seriously, and doing things like auditing your security. While you're less likely to get something very wrong, it's still a tradeoff. By using third party login services via OAuth, you tightly couple your service to them. Many people prefer not to use OAuth when offered because the application you're authenticating can obtain unnecessary information about the OAuth account with which you're authenticating. There's also the concern that OAuth can create a single point of failure for users; if they lose control of the service that they used for OAuth, all their disparate accounts become compromised.

So I think it's a good idea to put something about how it might be best for some devs to only use OAuth, I'm not sure a whole security item just saying "Prefer 3rd party OAuth" is warranted. Could there be a way to concisely communicate that devs would still need to choose to use only OAuth or implement their own authentication and the important considerations they need to take into account when choosing?

**Comment by goldbergyoni** [comment]
I agree with all the consequences and would suggest that we can find the phrasing that will make it true for 90% of the teams, hence it should be considered as a best practice. Note that one should not necessarily use social networks and data collectors like Google - The default should actually be services like Octa, Auth0 that provide finer control of the process and more privacy.

Suggesting first phrasing: "A modern authentication flow encompasses too many moving parts and potential failures. Unless an app has unique authentication requirements and a dedicated specialized team, using a reliable 3rd party for user management should be preferred"?

WDYT?
