### ISSUE TITLE
Component communication

### ISSUE THREAD

**Issue by criskurtin** [goldbergyoni/nodebestpractices#954]
Great list of best practices! A couple of questions though:

I'm struggling a bit with the concept of communication between components mentioned [here](https://github.com/goldbergyoni/nodebestpractices/blob/master/sections/projectstructre/breakintcomponents.md#one-paragraph-explainer). Is there any concrete, coded example of exposing a component through a public interface/API and consuming it in another component?
What if there's a need to use, say, a User model as a part of some Project model, both being components for themselves? 
I guess the main question is, how would one approach this "decoupling" of components while also consuming components elsewhere, and how to do it efficiently while not again ending up with dependency cobweb? The concept is there, and we all get it. But implementing this concept into the source itself is where questions like these arise.

I'd love to have a discussion about this topic with someone who has experience with this project structure :) I guess this struggle mainly comes from being so used to the traditional structuring by technical role and using it in almost all projects until now.

**Comment by JoelVenable** [comment]
I'm really enjoying the NestJS/Angular patterns to solve this particular issue.  

Basically, at the top level you have feature folders, plus maybe one or two top level folders for infrastructure.  Then inside each feature folder you then have "role" structured folders.  Each type of service has a naming convention (*.controller.ts, etc) that helps to segregate inside the feature folder.  If further segregation is needed, you could also expand into use-cases.

DTOs are POCO/POJO objects, VOs are Value Objects that perform validation and fail early on invalid input.  Controllers ONLY deal with the HTTP request/response objects and call service methods, where all the business logic lives.

The repository could be an ORM connection or could be its own folder if more complicated access patterns are needed.  Also note that a feature could include multiple models if that makes sense for the domain.

**Here is the key though**: Sometimes cross-service communication is needed, and that must happen from service to service.  Do not be tempted to bypass the service owner and fetch directly from the db in another domain's service/repository.

```
src
--| users
--|--| users.controller.ts
--|--| users.service.ts
--|--| users.repository.ts
--|--| dto
--|--|--| user-create.dto.ts
--|--| vo
--|--|--| user-create.vo.ts
--|--| use-cases
--|--|--| user-sign-in
--|--|--|--| user-sign-in.controller.ts
--|--|--|--| user-sign-in.service.ts
```

I readily admit that it is a "heavy" pattern with quite a bit of boilerplate, but it has definitely helped me stay sane...

Inspiration: 

https://github.com/Sairyss/domain-driven-hexagon

**Comment by goldbergyoni** [comment]
@criskurtin Welcome aboard. The communication must be done through the network (e.g. REST, MQ) and not direct in-process calls. The whole idea here is break into small problem - When I modify component A, I'm quite certain that I didn't break component B because they share nothing. Thanks to this, I deal with smaller problems and move faster. Yes, in reality, it is not that pure because coupling could also originate from npm libs and network calls. But when components share code, or directly access each other, the likelihood of spaghetti is much higher.

I like the overall structure of @JoelVenable (Welcome Joel!), use cases are always great, the repository pattern strikes a great balance between price and value, only 2 remarks on this:

- Folder per feature - It should be clear that a feature is an autonomous app with its own package.json and everything, otherwise the components/features are not really independent

- Service to service communication - This might encourage high-coupling between components, if A, B, C, D can approach E component's service, then the maintainer of E must conclude many clients when refactoring stuff while there is no semver or OpenAPI to manage this coupling

**Comment by abdellani** [comment]
Hi,

First, I want to thank you @goldbergyoni for this amazing project. I found it very useful.

When I was reading the document, I thought about the same question. In the given example, there are different components: orders, products, and users, etc...

I'm still confused about this approach. I'll describe the flow as I understood it and please correct me if I'm wrong:

* To follow **Folder per feature**, I guess that I'll also need to separate the features into different containers during the deployment, and the only way for them to communicate is through the network.

Imagine that in order to make an **order**, we need to check the user's balance (which is stored in the user model) and the availability of the product (which is stored in the product mode).

* To do those two validations, is it recommended to check directly the database? or to make two queries to the other components **User** and **Product**?

* How if the user wants to check the list of the ordered product details?  1 query to get the list of the orders, then for each order 1 query to get the product details? isn't it easier/faster to have direct access from the order component to the product model?

**Comment by josh-hemphill** [comment]
I'm not sure it's good to recommend sending all inter-component communication through the network, this means that all that data has to go from your CPU to your network controller and back (granted some CPUs have integrated network controllers); and the bandwidth capacity of your network controller is lower than the bandwidth of the CPU. Many applications go out of their way to implement IPC avoid the constraints and latency of the network controller. I'd actually been looking at using IPC in Nodejs for a secrets orchestration tool, since IPC can be a lot more selective about what gets to access the data stream and wouldn't burden the network controller if it were to also handle sending all the logs to a different process to handle shipping/federating them.
That's a bit of a tangent, but even though IPC is more complicated, I would prefer it to just blindly sending everything over the network. If you only need separation of concern, and not runtime process isolation, you could implement something like the dreaded event bus.

**Comment by goldbergyoni** [comment]
@abdellani @josh-hemphill Anything I recommended here is actually not my recommendation, it's the basic distributed component theory. Also known as "microservice". There is almost no Microservice guide that recommends against loosely coupled communication between components or recommends for sharing DB tables (very high coupling). I'm stating this because there are so many guides on this matter that will explain better than me.

The following might be the source of confusion:

1. Folder per **component**, not feature - When going full-blown, each component has its own repo. Why do we discuss folders here? Some prefer to start small with a monorepo (or just prefer monorepo over multi-repo), in this case each root folder represents a fully independent component that can potentially be a deployable unit 

2. This is not about inter-communication - @josh-hemphill This is about communication between external domains/context that are unlikely to be too chatty. In fact, when a good designer checks his own system decomposition, one of the tests is ensuring that only few interactions are needed between components during a flow

@abdellani Yes, a distributed app is inherently slower. We sacrifice (a bit) of runtime speed for a significant boost in deployment speed. In your order example, it's fair that the Order component will hold few a of the product fields in each order. There are other patterns to overcome this challenge (e.g. reporting component, BEF component and more).

**Comment by anthonygore** [comment]
Does anyone have an example repo showing the component-based structure in practice?

For me, I can't resolve how you deal with different database models using this structure. It doesn't seem practical to only use one model within that feature.
